name: dart_snmp
description: A dart library for communicating with simple network management protocol (snmp) enabled devices
version: 2.1.0
homepage: https://github.com/point-source/dart_snmp
repository: https://github.com/point-source/dart_snmp
issue_tracker: https://github.com/point-source/dart_snmp/issues

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  logging: ^1.0.1
  asn1lib: ^1.2.2

dev_dependencies:
  dart_code_metrics: ^5.0.1
  lints: ^2.0.1
  test: ^1.14.4
