name: dart_snmp
description: An snmp package for dart
version: 0.0.1
homepage: https://github.com/point-source/dart-snmp

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  asn1lib:
    git:
      url: git://github.com/point-source/asn1lib.git
      ref: snmp

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
